version: "3"

services:
    web:
        build:
            context: ./web
            dockerfile: ./Dockerfile
        container_name: auto-solar-web
        ports:
            - "8000:8000"
        volumes:
          - ./web:/usr/app
        entrypoint: python3 manage.py runserver 0.0.0.0:8000

networks:
  nginx:
    external: true
