version: "3"

services:
    web:
        build:
            context: ./web
            dockerfile: ./Dockerfile
        container_name: auto-solar-web
        ports:
            - "8000:8000"
        volumes:
          - ./web:/usr/app
