name: AutoSolar CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  test-auto-solar:
    name: Test AutoSolar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testing
      run: |
        docker-compose -f docker-compose-text.yaml up --build
