name: AutoSolar CI/CD pipeline

on:
  push:
    branches:
      - main

jobs:
  test-auto-solar:
    name: Test AutoSolar
    runs-on: ubuntu-latest
    container: python:3.10
    steps:
    - uses: actions/checkout@v3
    - name: Testing
      run: |
        cd auto_solar
        pip3 install -r requirements.txt
        pytest
